"""add language to posts

Revision ID: 06efc0bc93d6
Revises: 4cd99c49f01b
Create Date: 2020-06-08 13:38:58.788759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06efc0bc93d6'
down_revision = '4cd99c49f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
