"""Columna idioma.

Revision ID: 6da96445382f
Revises: 0ca0041e8299
Create Date: 2021-02-19 01:14:41.318615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da96445382f'
down_revision = '0ca0041e8299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('idioma', sa.String(length=5), nullable=True))
    op.drop_column('resource', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('language', sa.VARCHAR(length=5), nullable=True))
    op.drop_column('resource', 'idioma')
    # ### end Alembic commands ###
